# Generated by Django 5.2.1 on 2025-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='shown_questions',
            field=models.ManyToManyField(blank=True, to='core.question'),
        ),
    ]
